name: linux/amd64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  repository_dispatch: # Allows action to be triggered via webhook

  workflow_dispatch: # Allows action to be run manually from the Actions tab

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - name: Pull Latest Linux Base Image
        run: docker pull debian:buster-slim
      - name: Build Linux Image
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          file: ./linux.Dockerfile
          tags: |
            lacledeslan/gamesvr-goldsource-hldm:latest
            ghcr.io/lacledeslan/gamesvr-goldsource-hldm:latest
          build-args: |
            BUILDNODE=GitHub (Run Number: ${{ github.run_number }} Run ID: ${{ github.run_id }})
            SOURCE_COMMIT=${{ github.sha }}
          no-cache: true
      - name: Test Linux Image
        run: docker run --rm lacledeslan/gamesvr-goldsource-hldm:latest /app/ll-tests/gamesvr-goldsource-hldm.sh
      - name: Login to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Push to Docker HUB
        if: ${{ github.event_name != 'pull_request' }}
        run: docker push lacledeslan/gamesvr-goldsource-hldm:latest
      - name: Push to GitHub Packages
        if: ${{ github.event_name != 'pull_request' }}
        run: docker push ghcr.io/lacledeslan/gamesvr-goldsource-hldm:latest
